export const ProfileJson = [
	{
		label: 'Account Info',
		slug: 'account',
		iconName: 'userIcon',
		iconBg: '#EAEAEA',
		iconFg: '#000',
		iconActiveBg: '#F26E21',
		iconActiveFg: '#fff',
		iconSize: '20',
		borderColor: '#F5F5F5',
		bgColor: '#fff',
		fgColor: '#000',
		hoverBg: '#F5F5F5',
		hoverFg: '#000',
	},
	{
		label: 'My Orders',
		slug: 'orders',
		iconName: 'checklist',
		iconBg: '#EAEAEA',
		iconFg: '#000',
		iconActiveBg: '#F26E21',
		iconActiveFg: '#fff',
		iconSize: '20',
		hoverBg: '#F5F5F5',
		borderColor: '#F5F5F5',
		bgColor: '#fff',
		fgColor: '#000',
		hoverFg: '#000',
	},
	// {
	// 	label: 'Manage Address',
	// 	slug: 'address',
	// 	iconName: 'notes',
	// 	iconBg: '#EAEAEA',
	// 	iconFg: '#000',
	// 	iconActiveBg: '#F26E21',
	// 	iconActiveFg: '#fff',
	// 	iconSize: '20',
	// 	borderColor: '#F5F5F5',
	// 	bgColor: '#fff',
	// 	fgColor: '#000',
	// 	hoverBg: '#F5F5F5',
	// 	hoverFg: '#000',
	// },
	{
		label: 'FAQ',
		slug: 'faq',
		iconName: 'question',
		iconBg: '#EAEAEA',
		iconFg: '#000',
		iconActiveBg: '#F26E21',
		iconActiveFg: '#fff',
		iconSize: '20',
		hoverBg: '#F5F5F5',
		borderColor: '#F5F5F5',
		bgColor: '#fff',
		fgColor: '#000',
		hoverFg: '#000',
	},
];