const productDetailsData = [
  // {
  //   sectionTitle: "Heading",
  //   name: "productPage.headingBg",
  //   label: "Heading Background",
  //   type: "color",
  //   span: 1,
  // },
  // {
  //   name: "productPage.HeadingFg",
  //   label: "Heading Foreground",
  //   type: "color",
  //   span: 1,
  // },
  {
    sectionTitle: "Product Title",
    name: "productPage.titleColor",
    label: "Title Color",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.titleFontSizeBase",
    label: "Title Font Size Base",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.titleFontSizeBg",
    label: "Title Font Size BG",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.titleFontWeight",
    label: "Title Font Weight",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  // {
  // 	name: 'productPage.headingFontSize',
  // 	label: 'Heading Font Size',
  // 	type: 'number',
  // 	span: 1,
  // },
  // {
  // 	name: 'productPage.headingFontWeight',
  // 	label: 'Heading Font Weight',
  // 	type: 'number',
  // 	span: 1,
  // 	endOfSection: true,
  // },

  {
    sectionTitle: "Product Price",
    name: "productPage.priceColor",
    label: "Price Color",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.priceFontSizeBase",
    label: "Font Size Base",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.priceFontSizeBg",
    label: "Font Size BG",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.priceFontWeight",
    label: "Font Weight",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  {
    sectionTitle: "Badge",
    name: "productPage.badgeBg",
    label: "Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.badgeFg",
    label: "Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.badgeSecondaryFg",
    label: "Secondary Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.badgeFontWeight",
    label: "Font Weight",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.badgeRadius",
    label: "Badge Radius",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  // button css
  {
    sectionTitle: "Primary Button",
    name: "productPage.atcBtnBg",
    label: "Primary Button Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnFg",
    label: "Primary Button Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnHoberFg",
    label: "Primary Button Hover Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnHoverBg",
    label: "Primary Button Hover Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnRadius",
    label: "Primary Button Radius",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  // button css

  // primary css
  {
    sectionTitle: "Primary",
    name: "productPage.atcBtnFontSize",
    label: "Primary Font Size",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.atcBtnFontWeight",
    label: "Primary Font Weight",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.textPrimary",
    label: "Text Primary",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.textSecondary",
    label: "Text Secondary",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.borderRadius",
    label: "Image Border Radius",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  {
    sectionTitle: "Secondary Button",
    name: "productPage.secondaryBtnBg",
    label: "Secondary Button Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnFg",
    label: "Secondary Button Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnHoberFg",
    label: "Secondary Button Hover Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnHoverBg",
    label: "Secondary Button Hover Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnFontSize",
    label: "Secondary Button Font Size",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnFontWeight",
    label: "Secondary Button Font Weight",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnRadius",
    label: "Secondary Button Radius",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.textSecondary",
    label: "Text Secondary",
    type: "color",
    span: 1,
    endOfSection: true,
  },
];

export default productDetailsData;
