const cartSchema = [
	{
		name: 'shoppingCartCSS.bodyBg',
		label: 'Body Background',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.bodyFg',
		label: 'Body Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.borderColor',
		label: 'Border Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.checkoutBg',
		label: 'Checkout Background',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.checkoutFg',
		label: 'Checkout Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.checkoutHoverBg',
		label: 'Checkout Hover Background',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.checkoutHoverFg',
		label: 'Checkout Hover Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.checkoutTextSize',
		label: 'Checkout Text Size',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.checkoutTextWeight',
		label: 'Checkout Text Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.fTextSize',
		label: 'Footer Text Size',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.fTextWeight',
		label: 'Footer Text Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.footerBg',
		label: 'Footer Background',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.footerFg',
		label: 'Footer Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.headingBg',
		label: 'Heading Background',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.headingFg',
		label: 'Heading Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.headingSizeBase',
		label: 'Heading Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.headingSizeBg',
		label: 'Heading Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.priceSizeBase',
		label: 'Price Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.priceSizeBg',
		label: 'Price Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.qtyBg',
		label: 'Quantity Background',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.qtyFg',
		label: 'Quantity Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.removeFg',
		label: 'Remove Foreground',
		type: 'color',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.removeSize',
		label: 'Remove Size',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.titleSizeBase',
		label: 'Title Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.titleSizeBg',
		label: 'Title Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'shoppingCartCSS.titleWeight',
		label: 'Title Weight',
		type: 'number',
		span: 1,
	},
];

export default cartSchema;
