const checkoutCssSchema = [
	{
		name: 'checkoutCss.bgColor',
		label: 'Background Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.fgColor',
		label: 'Foreground Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.cardBg',
		label: 'Card Background Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.cardFg',
		label: 'Card Foreground Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.headingSizeBase',
		label: 'Heading Font Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.headingSizeBg',
		label: 'Heading Font Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.headingWeight',
		label: 'Heading Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.cardTitleSizeBase',
		label: 'Card Title Font Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.cardTitleSizeBg',
		label: 'Card Title Font Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.cardTitleWeight',
		label: 'Card Title Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.labelSize',
		label: 'Label Font Size',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.labelWeight',
		label: 'Label Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.inputBorder',
		label: 'Input Border Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.nameSizeBase',
		label: 'Name Font Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.nameSizeBg',
		label: 'Name Font Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.nameWeight',
		label: 'Name Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.nameColor',
		label: 'Name Font Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.qtySizeBase',
		label: 'Quantity Font Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.qtySizeBg',
		label: 'Quantity Font Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.qtyWeight',
		label: 'Quantity Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.qtyColor',
		label: 'Quantity Font Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.totalSizeBase',
		label: 'Total Font Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.totalSizeBg',
		label: 'Total Font Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.totalWeight',
		label: 'Total Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.totalColor',
		label: 'Total Font Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.summarySizeBase',
		label: 'Summary Font Size (Base)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.summarySizeBg',
		label: 'Summary Font Size (Big)',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.summaryWeight',
		label: 'Summary Font Weight',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.summaryColor',
		label: 'Summary Font Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.btnBg',
		label: 'Button Background Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.btnFg',
		label: 'Button Foreground Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.btnHoverBg',
		label: 'Button Hover Background Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.btnHoverFg',
		label: 'Button Hover Foreground Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'checkoutCss.btnSize',
		label: 'Button Font Size',
		type: 'number',
		span: 1,
	},
	{
		name: 'checkoutCss.btnWeight',
		label: 'Button Font Weight',
		type: 'number',
		span: 1,
	},
];

export default checkoutCssSchema;
