const aboutPageSchema = [
	{
		sectionTitle: 'AboutPage Css',
		name: 'aboutPage.bgColor',
		label: 'Background Color',
		type: 'color',
		span: 1,
	},
	{
		name: 'aboutPage.fgColor',
		label: 'Foreground Color',
		type: 'color',
		span: 1,
		endOfSection: true,
	},
	{
		sectionTitle: 'Banner Image',
		name: 'aboutPage.bannerImgSrc',
		label: 'Banner Image',
		type: 'image',
		span: 1,
	},
	{
		name: 'aboutPage.bannerText',
		label: 'Banner Text',
		type: 'string',
		span: 1,
		endOfSection: true,
	},
	{
		sectionTitle: 'About Mission',
		name: 'aboutPage.missionLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.missionParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.missionParagraphTwo',
		label: 'Paragraph Two',
		type: 'string',
		span: 1,
		endOfSection: true,
	},
	{
		sectionTitle: 'Product Range',
		name: 'aboutPage.productRangeLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.productRangeParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.productRangeParagraphTwo',
		label: 'Paragraph Two',
		type: 'string',
		span: 1,
		endOfSection: true,
	},

	{
		sectionTitle: 'Customer Centric Approach',
		name: 'aboutPage.customerCentricLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.customerCentricParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
		endOfSection: true,
	},
	{
		sectionTitle: 'Trusted Quality',
		name: 'aboutPage.trustedQualityLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.trustedQualityParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
		endOfSection: true,
	},
	{
		sectionTitle: 'Seamless Shopping',
		name: 'aboutPage.seamlessShoppingLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.seamlessShoppingParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
	},

	{
		sectionTitle: 'Reliable Delivery',
		name: 'aboutPage.reliableDeliveryLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.reliableDeliveryParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
		endOfSection: true,
	},

	{
		sectionTitle: 'Sustainable Practice',
		name: 'aboutPage.sustainablePracticeLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.sustainablePracticeParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
	},

	{
		sectionTitle: 'Community',
		name: 'aboutPage.communityLabel',
		label: 'Label',
		type: 'string',
		span: 1,
	},
	{
		name: 'aboutPage.communityParagraphOne',
		label: 'Paragraph One',
		type: 'string',
		span: 1,
		endOfSection: true,
	},
	{
		name: 'aboutPage.greetings',
		label: 'Greetings',
		type: 'string',
		span: 1,
		endOfSection: true,
	},
];

export default aboutPageSchema;
