const productDetailsData = [
  {
    sectionTitle: "Heading Colors",
    name: "productPage.headingBg",
    label: "Heading Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.HeadingFg",
    label: "Heading Foreground",
    type: "color",
    span: 1,
    endOfSection: true,
  },
  {
    sectionTitle: "Typography",
    name: "productPage.headingFontSize",
    label: "Heading Font Size",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.headingFontWeight",
    label: "Heading Font Weight",
    type: "number",
    span: 1,
    endOfSection: true,
  },

  {
    sectionTitle: "Add Cart Button Colors",
    name: "productPage.atcBtnBg",
    label: "Add To Cart Button Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnFg",
    label: "Add To Cart Button Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnHoberFg",
    label: "Add To Cart Button Hover Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.atcBtnHoverBg",
    label: "Add To Cart Button Hover Background",
    type: "color",
    span: 1,
  },

  {
    sectionTitle: "ATC Button Typography",
    name: "productPage.atcBtnFontSize",
    label: "Add To Cart Font Size",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.atcBtnFontWeight",
    label: "Add To Cart Font Weight",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.atcBtnRadius",
    label: "Add To Cart Button Radius",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  {
    sectionTitle: "Badge Colors",
    name: "productPage.badgeBg",
    label: "Badge Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.badgeFg",
    label: "Badge Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.badgeSecondaryFg",
    label: "Badge Secondary Foreground",
    type: "color",
    span: 1,
    endOfSection: true,
  },
  {
    sectionTitle: "Badge Typography",
    name: "productPage.badgeFontWeight",
    label: "Badge Font Weight",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.badgeRadius",
    label: "Badge Radius",
    type: "number",
    span: 1,
    endOfSection: true,
  },
  {
    name: "productPage.borderColor",
    label: "Border Color",
    type: "color",
    span: 1,
  },
  {
    sectionTitle: "Price Stylings",
    name: "productPage.priceColor",
    label: "Price Color",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.priceFontSizeBase",
    label: "Font Size Base",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.priceFontSizeBg",
    label: "Font Size BG",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.priceFontWeight",
    label: "Font Weight",
    type: "number",
    span: 1,
    endOfSection: true,
  },

  {
    sectionTitle: "Secondary Button Stylings",
    name: "productPage.secondaryBtnBg",
    label: "Secondary Button Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnFg",
    label: "Secondary Button Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnHoberFg",
    label: "Secondary Button Hover Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnHoverBg",
    label: "Secondary Button Hover Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnFontSize",
    label: "Secondary Button Font Size",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnFontWeight",
    label: "Secondary Button Font Weight",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.secondaryBtnRadius",
    label: "Secondary Button Radius",
    type: "number",
    endOfSection: true,
  },

  {
    sectionTitle: "Tab Stylings",
    name: "productPage.tabBg",
    label: "Tab Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.tabFg",
    label: "Tab Foreground",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.tabHoverBg",
    label: "Tab Hover Background",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.tabHoverFg",
    label: "Tab Hover Foreground",
    type: "color",
    span: 1,
    endOfSection: true,
  },

  {
    sectionTitle: "Text Stylings",
    name: "productPage.textPrimary",
    label: "Text Primary",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.textSecondary",
    label: "Text Secondary",
    type: "color",
    span: 1,
    endOfSection: true,
  },
  {
    sectionTitle: "Title Stylings",
    name: "productPage.titleColor",
    label: "Title Color",
    type: "color",
    span: 1,
  },
  {
    name: "productPage.titleFontSizeBase",
    label: "Title Font Size Base",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.titleFontSizeBg",
    label: "Title Font Size BG",
    type: "number",
    span: 1,
  },
  {
    name: "productPage.titleFontWeight",
    label: "Title Font Weight",
    type: "number",
    span: 1,
    endOfSection: true,
  },
];

export default productDetailsData;
